# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GirisEkraniUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(480, 306)
        self.label_3 = QtWidgets.QLabel(Form1)
        self.label_3.setGeometry(QtCore.QRect(290, 280, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(Form1)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 40, 321, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lneKullaniciAdi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneKullaniciAdi.setFont(font)
        self.lneKullaniciAdi.setObjectName("lneKullaniciAdi")
        self.verticalLayout_3.addWidget(self.lneKullaniciAdi)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lneSifre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneSifre.setFont(font)
        self.lneSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneSifre.setObjectName("lneSifre")
        self.verticalLayout.addWidget(self.lneSifre)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(Form1)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 190, 321, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSifreUnutma = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSifreUnutma.setFont(font)
        self.btnSifreUnutma.setObjectName("btnSifreUnutma")
        self.verticalLayout_2.addWidget(self.btnSifreUnutma)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnGirisYap = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGirisYap.setFont(font)
        self.btnGirisYap.setObjectName("btnGirisYap")
        self.horizontalLayout.addWidget(self.btnGirisYap)
        self.btnKayitOl = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnKayitOl.setFont(font)
        self.btnKayitOl.setObjectName("btnKayitOl")
        self.horizontalLayout.addWidget(self.btnKayitOl)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.lblBilgilendirmeGiris = QtWidgets.QLabel(Form1)
        self.lblBilgilendirmeGiris.setGeometry(QtCore.QRect(80, 10, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBilgilendirmeGiris.setFont(font)
        self.lblBilgilendirmeGiris.setObjectName("lblBilgilendirmeGiris")

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Giriş yapın"))
        self.label_3.setText(_translate("Form1", "Designed by Simo Hayha"))
        self.label.setText(_translate("Form1", "Kullanıcı Adı:"))
        self.label_2.setText(_translate("Form1", "Şifre:"))
        self.btnSifreUnutma.setText(_translate("Form1", "Şifrenizi mi unuttunuz?"))
        self.btnGirisYap.setText(_translate("Form1", "Giriş yap"))
        self.btnKayitOl.setText(_translate("Form1", "Kayıt ol"))
        self.lblBilgilendirmeGiris.setText(_translate("Form1", "<html><head/><body><p><span style=\" color:#ef0a28;\">dasdsadsads</span></p></body></html>"))

