# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KayitEkraniUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(416, 456)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 191, 52))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lneYeniKayitSifre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneYeniKayitSifre.setFont(font)
        self.lneYeniKayitSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneYeniKayitSifre.setObjectName("lneYeniKayitSifre")
        self.verticalLayout_2.addWidget(self.lneYeniKayitSifre)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 210, 191, 52))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lneYeniKayitTelNo = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneYeniKayitTelNo.setFont(font)
        self.lneYeniKayitTelNo.setAutoFillBackground(False)
        self.lneYeniKayitTelNo.setMaxLength(15)
        self.lneYeniKayitTelNo.setPlaceholderText("")
        self.lneYeniKayitTelNo.setClearButtonEnabled(False)
        self.lneYeniKayitTelNo.setObjectName("lneYeniKayitTelNo")
        self.verticalLayout_4.addWidget(self.lneYeniKayitTelNo)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 150, 191, 52))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lneYeniKayitMailAdresi = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneYeniKayitMailAdresi.setFont(font)
        self.lneYeniKayitMailAdresi.setPlaceholderText("")
        self.lneYeniKayitMailAdresi.setObjectName("lneYeniKayitMailAdresi")
        self.verticalLayout_3.addWidget(self.lneYeniKayitMailAdresi)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 191, 52))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget3.setFont(font)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lneYeniKayitKullaniciAdi = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneYeniKayitKullaniciAdi.setFont(font)
        self.lneYeniKayitKullaniciAdi.setObjectName("lneYeniKayitKullaniciAdi")
        self.verticalLayout.addWidget(self.lneYeniKayitKullaniciAdi)
        self.btnKaydol = QtWidgets.QPushButton(Form)
        self.btnKaydol.setGeometry(QtCore.QRect(260, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnKaydol.setFont(font)
        self.btnKaydol.setObjectName("btnKaydol")
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 300, 357, 54))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget4.setFont(font)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBilgilendirmeMetni = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBilgilendirmeMetni.setFont(font)
        self.checkBilgilendirmeMetni.setObjectName("checkBilgilendirmeMetni")
        self.verticalLayout_5.addWidget(self.checkBilgilendirmeMetni)
        self.checkReklam = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkReklam.setFont(font)
        self.checkReklam.setObjectName("checkReklam")
        self.verticalLayout_5.addWidget(self.checkReklam)
        self.lblBilgilendirme = QtWidgets.QLabel(Form)
        self.lblBilgilendirme.setGeometry(QtCore.QRect(10, 400, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBilgilendirme.setFont(font)
        self.lblBilgilendirme.setText("")
        self.lblBilgilendirme.setObjectName("lblBilgilendirme")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kaydolma"))
        self.groupBox.setTitle(_translate("Form", "Kayıt işlemleri"))
        self.label_2.setText(_translate("Form", "Şifre:"))
        self.label_4.setText(_translate("Form", "Telefon numaranız:"))
        self.lneYeniKayitTelNo.setInputMask(_translate("Form", "(999) 999 99 99"))
        self.lneYeniKayitTelNo.setText(_translate("Form", "()   "))
        self.label_3.setText(_translate("Form", "Mail adresiniz:"))
        self.label.setText(_translate("Form", "Kullanıcı adı:"))
        self.btnKaydol.setText(_translate("Form", "Kaydol"))
        self.checkBilgilendirmeMetni.setText(_translate("Form", "Bilgilendirme metnini okudum ve onaylıyorum."))
        self.checkReklam.setText(_translate("Form", "Reklam e-postaları gelmesini kabul ediyorum."))

