# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SifremiUnuttumEkraniUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form3(object):
    def setupUi(self, Form3):
        Form3.setObjectName("Form3")
        Form3.resize(429, 448)
        self.groupBox = QtWidgets.QGroupBox(Form3)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 351, 351))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 290, 222, 52))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.lneYeniSifreDogrula = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneYeniSifreDogrula.setFont(font)
        self.lneYeniSifreDogrula.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneYeniSifreDogrula.setObjectName("lneYeniSifreDogrula")
        self.verticalLayout_6.addWidget(self.lneYeniSifreDogrula)
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 230, 222, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lneYeniSifre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneYeniSifre.setFont(font)
        self.lneYeniSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneYeniSifre.setObjectName("lneYeniSifre")
        self.verticalLayout_5.addWidget(self.lneYeniSifre)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 221, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lneUnutKullaniciAdi = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneUnutKullaniciAdi.setFont(font)
        self.lneUnutKullaniciAdi.setObjectName("lneUnutKullaniciAdi")
        self.verticalLayout.addWidget(self.lneUnutKullaniciAdi)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lneMailAdresi = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneMailAdresi.setFont(font)
        self.lneMailAdresi.setObjectName("lneMailAdresi")
        self.verticalLayout.addWidget(self.lneMailAdresi)
        self.btnKodlariGonder = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnKodlariGonder.setFont(font)
        self.btnKodlariGonder.setObjectName("btnKodlariGonder")
        self.verticalLayout.addWidget(self.btnKodlariGonder)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 170, 221, 52))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lneEmailKod = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneEmailKod.setFont(font)
        self.lneEmailKod.setMaxLength(6)
        self.lneEmailKod.setObjectName("lneEmailKod")
        self.verticalLayout_3.addWidget(self.lneEmailKod)
        self.btnSifreyiDegistir = QtWidgets.QPushButton(Form3)
        self.btnSifreyiDegistir.setGeometry(QtCore.QRect(250, 370, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSifreyiDegistir.setFont(font)
        self.btnSifreyiDegistir.setObjectName("btnSifreyiDegistir")
        self.lblBilgilendirmeSifremiUnuttum = QtWidgets.QLabel(Form3)
        self.lblBilgilendirmeSifremiUnuttum.setGeometry(QtCore.QRect(40, 370, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBilgilendirmeSifremiUnuttum.setFont(font)
        self.lblBilgilendirmeSifremiUnuttum.setText("")
        self.lblBilgilendirmeSifremiUnuttum.setObjectName("lblBilgilendirmeSifremiUnuttum")

        self.retranslateUi(Form3)
        QtCore.QMetaObject.connectSlotsByName(Form3)

    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "Şifrenizi yenileyin"))
        self.label_6.setText(_translate("Form3", "Yeni şifrenizi doğrulayın:"))
        self.label_5.setText(_translate("Form3", "Yeni şifre:"))
        self.label.setText(_translate("Form3", "Kullanıcı adınız:"))
        self.label_2.setText(_translate("Form3", "Mail adresiniz:"))
        self.btnKodlariGonder.setText(_translate("Form3", "Kodu gönder"))
        self.label_4.setText(_translate("Form3", "E-Mailinize gelen kod:"))
        self.lneEmailKod.setPlaceholderText(_translate("Form3", "xxxxxx@xxxxx.com"))
        self.btnSifreyiDegistir.setText(_translate("Form3", "Şifreyi değiştir"))

